### ISSUE TITLE
pretty-derivation leaks memory

### ISSUE THREAD

**Issue by mweinelt** [Gabriel439/Haskell-Nix-Derivation-Library#11]
I'm trying to pretty-print the derivation of `zigbee2mqtt` in this branch https://github.com/NixOS/nixpkgs/pull/114896. After ~22 GB RAM used earlyoom decides to kill the process.

**Comment by Gabriel439** [comment]
The fix is up here: https://github.com/Gabriel439/Haskell-Nix-Derivation-Library/pull/13

I tested that against the `zigbee2mqtt` derivation.  Before the fix I was able to reproduce the leak and after the fix it now takes about 1-2 seconds to print the derivation.

**Comment by mweinelt** [comment]
Thank you. I've been using nix-derivation from within nixpkgs, so I'm not in a position to test drive this change.
