### ISSUE TITLE
Hashable instance?

### ISSUE THREAD

**Issue by jsoo1** [Gabriel439/Haskell-Nix-Derivation-Library#18]
It might be nice to make unordered collections of derivations. Would a `Hashable` instance would be nice for `Derivation`?

**Comment by Gabriel439** [comment]
I took a stab at doing this and the main issue that I ran into is that `Set` doesn't have a `Hashable` instance, so `Hashable` cannot be derived for the `Derivation` type

**Comment by jsoo1** [comment]
Ah I see. Ok then. I suppose I can find another way. Thank you!

**Comment by Gabriel439** [comment]
You're welcome!
